pyprland.plugins = [ "scratchpads" ]

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
match_by = "initialTitle"
initialTitle = "re:Spotify.*"
size = "80% 75%"

[scratchpads.hmm]
animation = "fromBottom"
command = "[term_classed] h-m-m-todo-scratch --title='h-m-m' h-m-m ~/todo.hmm"
class = "h-m-m-todo-scratch"
size = "96% 80%"
margin = "8%"
lazy = true

[scratchpads.vesktop]
animation = "fromBottom"
command = "vesktop"
class = "vesktop"
position = "1% 5%"
size = "98% 94%"
lazy = true
